### ISSUE TITLE
Error `Failed to find entry-points:` on 2021.3+ with assembly validation

### ISSUE THREAD

**Issue by hybridherbst** [needle-tools/package-credentials#2]
Looks like we need to turn "Validate References" off (?):
![image](https://user-images.githubusercontent.com/2693840/220401286-461a6989-0dac-484f-b279-4dda3b9d6485.png)

**Comment by Etruscian** [comment]
This has been plaguing me ever since I updated. Any progress on this?

**Comment by hybridherbst** [comment]
It’s a bug in Unity’s Burst but we haven’t heard back from them so far. I’ll try to check if there’s a workaround with renaming them

**Comment by hybridherbst** [comment]
Should be fixed on 1.2.0
